### ISSUE TITLE
Unable to find service 

### ISSUE THREAD

**Issue by andruwa13** [josmo/drone-rancher#20]
Hello, help please. I throw an error when deploying *drone io* on rancher `Unable to find service demo/wordpress3`
```
rancher:
  image: peloton/drone-rancher
  url: http://*****:8080
  access_key: ***
  secret_key: ******
  service: demo/wordpress3
  docker_image: registry.gitlab.com/*****/******
```

![rancher_2017-04-02_02-08-22](https://cloud.githubusercontent.com/assets/5846351/24583478/febaa124-1753-11e7-8c84-470b6a57e677.png)
