### ISSUE TITLE
The plugin isn't able to find my stacks anymore

### ISSUE THREAD

**Issue by Vesli** [josmo/drone-rancher#32]
Hello, I've like 10 environments and each of them contains ~10 stacks (with 2 to 3 containers per stack) and everything was working well until I added a new Env.

In this rancher env I've added 8 stacks, when I deploy with drone, 7 of those stacks works well, but anything after this 7th return in drone:

> Unable to find stack <stack name>

I've added a 8th and 9th one.. none of them will be found by the plugin.

<img width="1110" alt="screen shot 2018-02-21 at 12 13 16" src="https://user-images.githubusercontent.com/10052941/36479442-a61a68b2-1700-11e8-867f-db4f84f2f704.png">

**Comment by josmo** [comment]
Hi @Vesli can you give details on the environment and the .drone.yml?  I've never seen that problem before and I've had larger setups.

**Comment by Vesli** [comment]
Sure, let's take this example:
<img width="1430" alt="screen shot 2018-02-22 at 10 34 01" src="https://user-images.githubusercontent.com/10052941/36533617-f8432c12-17bb-11e8-99a1-1b2aa4931d4d.png">

We have 5 stacks in this env. Each stacks has 1 to 3 containers - which I agree with you, is nothing terrific.

If I add one more stack to this env, drone result with my initial error "can't find the stack".
Concerning the drone file, here is the one we recently used and had this error:

```
pipeline:

  ## Master
  push-master:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: docker.domain.com:5000/descartes
    registry: docker.domain.com:5000
    tags: "latest"
    when:
      event: push
      branch: master

  rancher-deploy-master:
    image: peloton/drone-rancher
    url: http://rancher.domain.com:8080
    secrets: [ plugin_access_key, plugin_secret_key ]
    service: descartes/nomad
    docker_image:  docker.heyolly.com:5000/descartes:latest
    start_first: true
    time_out: 120
    when:
      event: push
      branch: master

  ## Dev
  push-dev:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: docker.domain.com:5000/descartes
    registry: docker.domain.com:5000
    tags: "dev"
    when:
      event: push
      branch: dev

  rancher-deploy-dev:
    image: peloton/drone-rancher
    url: http://rancher.domain.com:8080
    secrets: [ plugin_access_key, plugin_secret_key ]
    service: descartes-dev/descartes
    docker_image:  docker.domain.com:5000/descartes:dev
    start_first: true
    time_out: 120
    when:
      event: push
      branch: dev

  ## Feature branches.
  push-feature:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: docker.domain.com:5000/descartes
    registry: docker.domain.com:5000
    tags: "feature"
    when:
      event: push
      branch:
        exclude: [ dev, master, test-* ]

    ## Testing branch
  push-staging:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: docker.domain.com:5000/descartes
    registry: docker.domain.com:5000
    tags: ${DRONE_COMMIT_BRANCH}
    when:
      branch: test-*

  rancher-deploy-staging:
    image: peloton/drone-rancher
    url: http://rancher.domain.com:8080
    secrets: [ plugin_access_key, plugin_secret_key ]
    service: vision-staging/Descartes #this was an other stack, but we had to remove it as it was producing the error***
    docker_image:  docker.domain.com:5000/descartes:${DRONE_COMMIT_BRANCH}
    start_first: true
    time_out: 120
    when:
      branch: test-*


  ###
   # NOTIFY build
  ###
  notify-build:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/aosifu1948UIAO
    channel: jenkins
    username: The Mighty Pokeball
    template: >
      {{#success build.status}}
        Build {{build.link}} succeeded on {{repo.name}} from branch {{uppercase build.branch}}!
      {{else}}
        Build {{build.link}} failed! {{repo.name}} from branch {{uppercase build.branch}}
      {{/success}}
    when:
      status: [ failure ]
```

*** the stack name was Descartes-staging/descartes and was failing.
