### ISSUE TITLE
Confirm fails

### ISSUE THREAD

**Issue by Miminoux** [josmo/drone-rancher#8]
Hi,

I have a problem for the confirmation step, it ends up with status code "1" but there is no line printed out whereas I read in the main.go that there should be either : 
- "Error waiting for service upgrade to complete" if after 30 seconds the service wouldn't be upgraded (the service is updated in time)
- "Unable to finish upgrade" if the method ActionFinishupgrade would have returned an error
- "Finished upgrade" if everything went fine

Here is the log output : 
[info] Pulling image artifactory.myoffice.me.fr:5001/drone-rancher:latest
Drone Rancher Plugin built at 2016-02-02 08:56:57 UTC
Upgraded glpi/glpi to docker:artifactory.myoffice.me:5003/glpi:latest
[info] build failed (exit code 1)

On Rancher, the service is upgraded but not confirmed.

Here is the deploy part of my .drone.yml : 
deploy:
  rancher:
    image: artifactory.myoffice.me:5001/drone-rancher:latest
    url: 'https://rancher.myoffice.me'
    access_key: xxx
    secret_key: xxx
    service: glpi/glpi
    docker_image: 'artifactory.myoffice.me:5003/glpi:latest'
    start_first: true
    confirm: true

Any idea ?

Thx

**Comment by qrpike** [comment]
Set the timeout higher

**Comment by cusspvz** [comment]
Same here. https://github.com/drone/drone/issues/1663#issue-158401177

**Comment by jandragsbaek** [comment]
I am seeing this too.

Tried with timeout at different values, with same results. It seems like it is waiting for something. Last log lines are:

```
[info] Pulling image plugins/drone-rancher:latest
Drone Rancher Plugin built from b4cd686
Upgraded micro-tools/app to docker:docker.falconsocial.com/tools/micro-tools:latest
```

**Comment by rgauny** [comment]
+1

Having the same issue

**Comment by cusspvz** [comment]
@rgauny Increase the timeout.

Example:

``` yaml
  rancher:
    url: https://xxx
    access_key: xxx
    secret_key: xxx
    service: xxx/xxx
    docker_image: xxx/xxx:$$COMMIT
    start_first: true
    confirm: true
    timeout: 180
    when:
      branch:
        - xxx

```
